[[section-architecture-constraints]]
== Architecture Constraints


[role="arc42help"]
****
.Contents
En este proyecto vamos a tener varias restricciones de arquitectura:

* Restricción temporal: tenemos aproximadamente un cuatrimestre para tener una versión de lanzamiento de la aplicación.
* Restricción de alcance: esta app tiene como función que los usuarios puedan realizar como mínimo diferentes funciones como guardar lugares; asociar puntuaciones, comentarios y o fotos a los lugares; visualizarlos en un mapa; informarse sobre estos; filtrar las ubicaciones. Además se debe respetar la privacidad de cada usuario en la medida de lo posible.
* La información sobre los lufares de cada usuario se debe guardar en su pod personal.

.Motivation
Architects should know exactly where they are free in their design decisions and where they must adhere to constraints.
Constraints must always be dealt with; they may be negotiable, though.

.Form
Simple tables of constraints with explanations.
If needed you can subdivide them into
technical constraints, organizational and political constraints and
conventions (e.g. programming or versioning guidelines, documentation or naming conventions)
****
