[[section-runtime-view]]
== Runtime View
Por el momento el contenido de este apartado no es muy extenso debido a la pronta etapa rn la que se encuentra em proyecto, a medida que se vaya avanzando este documento se irá actualizando y enriqueciendo.

[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== Edit web ID
Cuando un usuario quiere cambiar el Web ID:

[plantuml,"Sequence diagram",png]
----
header Runtime View
title WebID change
Actor User
Participant LoMap
Database DataBase as "DataBase" 

...User log in as shown......

User -> LoMap: Asks for WebID change
User <-- LoMap: Show edit menu to User
User -> LoMap: Provide the new WebID
LoMap --> LoMap: Verify WebID

...LoMap wait till get POD permissions......

LoMap -> DataBase: Update user credentials
LoMap <-- DataBase: Confirm credentials

LoMap -> User: Show confirm dialog

...User log out as shown......
----
=== Login and Logout
El proceso de login y logout para poder ser reconocido por la applicación:
[plantuml,"Log in - log out sequence diagram",png]
----
header Runtime View
title Log in - Log out
Actor User
Participant LoMap
Database DataBase as "DataBase" 

User -> LoMap: Log in with his credentials
LoMap -> DataBase: Check user credentials
LoMap <-- DataBase: Confirm credentials

...User interacts with the apllication......

User -> LoMap: Log out from apllication
LoMap --> User: Show exit dialog and closes user session
----

=== User Sign Up
El proceso de crear un nuevo usuario para poder hacer log in
[plantuml,"Register sequence diagram",png]
----
header Runtime View
title User Registration
Actor User
Participant LoMap
Database DataBase as "DataBase" 

User -> LoMap: Sing up as a new user
User <-- LoMap: Ask user for his WebID
User --> LoMap: Bring his WebID
LoMap --> LoMap: Verify WebID

...LoMap wait till get POD permissions......

LoMap -> DataBase: Add user credentials
LoMap <-- DataBase: Confirm credentials addition
User <- LoMap: Show confirm dialog to User
----

=== Place adding
El proceso de añadir un lugar al mapa:
[plantuml,"Add favorite place sequence diagram",png]
----
header Runtime View
title Add favorite place
Actor User
Participant LoMap
Database DataBase as "User's POD" 

...User log in as shown......

User -> LoMap: Wanna add a place
User <-- LoMap: Show favorite places form
User -> LoMap: Provide the info

LoMap -> DataBase: Add new user data
LoMap <-- DataBase: Confirm data addition

LoMap -> User: Show confirm dialog

...User log out as shown......

----
