[[section-deployment-view]]


== Deployment View

[role="arc42help"]
****
.Content
The deployment view describes:

 1. the technical infrastructure used to execute your system, with infrastructure elements like geographical locations, environments, computers, processors, channels and net topologies as well as other infrastructure elements and

2. the mapping of (software) building blocks to that infrastructure elements.

Often systems are executed in different environments, e.g. development environment, test environment, production environment. In such cases you should document all relevant environments.

Especially document the deployment view when your software is executed as distributed system with more then one computer, processor, server or container or when you design and construct your own hardware processors and chips.

From a software perspective it is sufficient to capture those elements of the infrastructure that are needed to show the deployment of your building blocks. Hardware architects can go beyond that and describe the infrastructure to any level of detail they need to capture.

.Motivation
Software does not run without hardware.
This underlying infrastructure can and will influence your system and/or some
cross-cutting concepts. Therefore, you need to know the infrastructure.

.Form

Maybe the highest level deployment diagram is already contained in section 3.2. as
technical context with your own infrastructure as ONE black box. In this section you will
zoom into this black box using additional deployment diagrams:

* UML offers deployment diagrams to express that view. Use it, probably with nested diagrams,
when your infrastructure is more complex.
* When your (hardware) stakeholders prefer other kinds of diagrams rather than the deployment diagram, let them use any kind that is able to show nodes and channels of the infrastructure.
****

=== Infrastructure Level 1

[role="arc42help"]
****


 .Motivation
En el entorno de testing la app se ejecutará en los ordenadores de la universidad y en los ordenadores personales de los desarrolladores de la aplicación. Sin embargo en el entorno de lanzamiento el objetivo es que cualquier ciudadano en bruselas pueda ejecutar la aplicación desde su propio dispositivo.


.Motivation
En el entorno de testing la app se ejecutará en los ordenadores de los desarrolladores de la aplicación.
En este punto del desarrollo de la aplicación no es posible especificar cuál será la estructura de lanzamiento. 
Más adelante en el desarrollo del proyecto de completará la documentación para representar de forma fiel como se desplegará la aplicación.


.Quality and/or Performance Features
La predicción es que nuestra aplicación va a tener dependencias con numerosas APIs. Tanto la API que usemos para el servicio de mapas como la usada para manejar los PODs no depende de nosotros.
Estas dependencias externas provocan que el rendimiento y disponibilidad de nuestra aplicación se vea condicionada por estos servicios. En una etapa más madura del desarrollo se medirán tiempos de espera para poder concretar el rendimiento medio de la aplicación.

.Mapping of building blocks to infrastructure

Nuestra infraestructura estará formada por los siguientes elementos:

* PODs: Almacen individual de información, garantiza la privacidad del usuario.
* Servidor: Contenedor de nuestra aplicación para despliegue. Todavía sin concretar.
* WebApp: Front-end de nuestra aplicación.
* RestApi: Back-end de nuestra aplicación.
* MongoDB: En este punto, base de datos elegida para la aplicación. Con el uso de MongoDB Atlas para su despliegue.

Nuestra infraestructura estará formada por los siguientes elementos:
PODS: Se utilizarán para guardar datos privados.
Servidor: Contendrá una base de datos con información de la app.
WebApp: Mostrará la interfaz al usuario.
RestApi: Será el encargado de la lógica de negocio.


